

TASK[X] 
/**
 * Calcular se aluno foi aprovado ou não: 
 * ENTRADA: Um numero
 *  * LOGICA: 
 *    - ???
 * SAIDA: Mensaje sobre se foi aprovado ou não
 * VALIDAÇÃO: Mostrar um mensage de error se o valor ingressado está fora do rango
 */


TASK[X] 
/**
 * Calcular se um numero é positivo, negativo ou zero: 
 * ENTRADA: 
 * LOGICA: 
 *  * LOGICA: 
 *    - ???
 * VALIDAÇÃO: 
 */


TASK[X] 
/**
 * Calcular se um numero é par ou impar: 
 * ENTRADA: 
 * LOGICA: 
 *  * LOGICA: 
 *    - ???
 * VALIDAÇÃO: 
 */


TASK[X] 
/**
 * Calcular se a letra ingressada é uma vocal: 
 * ENTRADA: 
 * LOGICA: 
 *  * LOGICA: 
 *    - ???
 * VALIDAÇÃO: 
 */



TASK[X] 
/**
 * Simular um termometro digital: 
 * ENTRADA: Um numero
 *  * LOGICA: 
 *    - ???
  * SAIDA: Mensaje sobre o como está o clima
 * VALIDAÇÃO: Mostrar um mensage de error se o valor ingressado está fora do rango
 */


TASK[X] 
/**
 * Simular um semaforo: 
 * ENTRADA: Uma cor (verde, vermelho, amarelo)
 * LOGICA:
 *  - 
 * OUTPUT: Mensaje para a pessoa que vai atravesar a rua
 * SAIDA: Mostrar um mensage de error se o valor ingressado está fora do rango
 */


TASK[X] 
/* Solicitar um numero ao usuario (1-12) e mostrar o nome do mes desse numero.
Por exemplo: 1 seria "Janeiro", ......
VALIDAÇÃO: Mostrar um mensage de error se o valor ingressado está fora do rango
*/